### ISSUE TITLE
conda installed libreadline fails R to start

### ISSUE THREAD

**Issue by haobibo** [conda-forge/rpy2-feedstock#1]
Currently, rpy2 requires libreadline.so.6 package, which is also provided by conda (https://github.com/conda-forge/rpy2-feedstock/blob/master/recipe/meta.yaml#L43).
But after install rpy2, R will not start due to `/opt/conda/lib/R/bin/exec/R: symbol lookup error: /opt/conda/lib/R/bin/exec/../../lib/../../libreadline.so.6: undefined symbol: PC`.

This bug is also mentioned in these issues:
 - https://github.com/IRkernel/IRkernel/issues/204
 - https://github.com/ContinuumIO/anaconda-issues/issues/152

Although other users provide some workarounds, e.g.:`cp -p /lib/x86_64-linux-gnu/libreadline.so.6 $CONDA_DIR/lib/libreadline.so.6`, but why is conda's readline different from the system's default libreadline.so.6 ? Or maybe conda should allow users to use their libreadline.so.6 if it already exists in system's lib directory instead of install one in `$CONDA_DIR/lib` ?

Environment:

```
Current conda install:

               platform : linux-64
          conda version : 4.3.21
       conda is private : False
      conda-env version : 4.3.21
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.18.1
       root environment : /opt/conda  (writable)
    default environment : /opt/conda
       envs directories : /opt/conda/envs
                          /root/.conda/envs
          package cache : /opt/conda/pkgs
                          /root/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/r/linux-64
                          https://conda.anaconda.org/r/noarch
            config file : /root/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.21 requests/2.18.1 CPython/3.6.1 Linux/4.4.0-77-generic debian/stretch/sid glibc/2.23
                UID:GID : 0:0
```

**Comment by jhunkeler** [comment]
https://github.com/ContinuumIO/anaconda-recipes/issues/56
https://github.com/ContinuumIO/anaconda-recipes/pull/60

Good luck.

**Comment by endrebak** [comment]
`conda install readline` from conda-forge worked for me.

**Comment by leipzig** [comment]
conda install -c conda-forge readline=6.2

**Comment by oneklc** [comment]
`conda install -c conda-forge readline=6.2`
Didn't work for me.  As 6.2 was already installed. 

`conda upgrade -c conda-forge readline`
upgraded readline to 7.0 for the win!
