### ISSUE TITLE
ImportError: libgfortran.so.3: cannot open shared object file

### ISSUE THREAD

**Issue by huidongchen** [conda-forge/rpy2-feedstock#20]
Hi 

I'm trying to update a biconda recipe 'stream' but got some unexpected errors. Björn suggested to me that it might be related to rpy2. https://github.com/bioconda/bioconda-recipes/issues/14550. When you have a minute, I would be really grateful if you could help take a look .

Thanks a lot!

**Comment by isuruf** [comment]
Please try the latest build and reopen if this is still an issue
